# Generated by Django 5.0.5 on 2024-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='general_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='twobigfeetninja@gmail.com', max_length=50)),
                ('phone', models.IntegerField(default='0712-345-678')),
                ('web_app_name', models.TextField(default='glowing up')),
                ('location', models.TextField(default='Kenya')),
                ('open_hours', models.CharField(default='9-5, every weekday', max_length=50)),
            ],
        ),
    ]
